spring:
  application:
    name: ThayCuongLee_BE
  datasource:
    url:
    username:
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  flyway:
    enabled: true
    baseline-version: 1

app:
  jwt-secret-key: cw0Fg7PcBjEuZ9d0N4zz07HGoYF7ir7XhjWQhAwp3Gg682MYwxv9YORI6gncR/Jw5E390qH4WYl/jdvrkfdahg==