ALTER TABLE users
ADD COLUMN IF NOT EXISTS role VARCHAR(50);

UPDATE users
SET role = 'MEMBER'
WHERE role IS NULL;

ALTER TABLE users
ALTER COLUMN role SET DEFAULT 'MEMBER',
ALTER COLUMN role SET NOT NULL;

ALTER TABLE users
DROP CONSTRAINT IF EXISTS ck_users_role,
ADD CONSTRAINT ck_users_role CHECK (role IN ('ADMIN', 'MEMBER'));